version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - ./Front:/app/
      - /app/node_modules
    networks:
      - wordle_network
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./Back:/app/
    networks:
      - wordle_network

networks:
  wordle_network:
    driver: bridge
