# Используем Node.js образ для разработки
FROM node:16

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json для установки зависимостей
COPY Front/package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь исходный код проекта
COPY Front/ .

# Запускаем сервер разработки Vue.js
CMD ["npm", "run", "serve"]

# Экспонируем порт 8080 (по умолчанию используется сервер Vue)
EXPOSE 8080
