version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "sqlite+aiosqlite:///test.db"  # Указываем ту же строку, что и в Python файле
    volumes:
      - .:/app  # Монтируем локальную папку для обновления кода без пересборки контейнера
